
version: 2

models:
    - name: mn_zip
      config:
        contract:
          enforced: true
      description: "Minnesota Zip Codes"
      columns:
        - name: zip_id
          data_type: number
          constraints:
            - type: not_null
            - type: unique
          tests:
            - unique
        - name: zip
          data_type: varchar
          constraints:
            - type: not_null
            - type: unique
          tests:
            - unique
        - name: SourceSystem
          data_type: varchar
        - name: City
          data_type: varchar
        - name: State
          data_type: varchar
